### ISSUE TITLE
Builds failing due to scikit-allel

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tutorials#245]
E.g. on https://github.com/tskit-dev/tutorials/pull/244. I think we have seen this before, @benjeffery, so I think there's a simple fix, right?

```
Collecting scikit-allel==1.3.5
[624](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:625)
  Downloading scikit-allel-1.3.5.tar.gz (9.7 MB)
[625](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:626)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 32.7 MB/s eta 0:00:00
[626](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:627)
  Installing build dependencies: started
[627](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:628)
  Installing build dependencies: finished with status 'done'
[628](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:629)
  Getting requirements to build wheel: started
[629](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:630)
  Getting requirements to build wheel: finished with status 'error'
[630](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:631)
  error: subprocess-exited-with-error
[631](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:632)
  
[632](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:633)
  × Getting requirements to build wheel did not run successfully.
[633](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:634)
  │ exit code: 1
[634](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:635)
  ╰─> [36 lines of output]
[635](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:636)
      [scikit-allel] setup extensions with cython
[636](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:637)
      Compiling allel/opt/model.pyx because it changed.
[637](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:638)
      Compiling allel/opt/stats.pyx because it changed.
[638](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:639)
      Compiling allel/opt/io_vcf_read.pyx because it changed.
[639](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:640)
      [1/3] Cythonizing allel/opt/io_vcf_read.pyx
[640](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:641)
      [2/3] Cythonizing allel/opt/model.pyx
[641](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:642)
      [3/3] Cythonizing allel/opt/stats.pyx
[642](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:643)
      Traceback (most recent call last):
[643](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:644)
        File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
[644](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:645)
          main()
[645](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:646)
        File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
[646](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:647)
          json_out['return_val'] = hook(**hook_input['kwargs'])
[647](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:648)
        File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
[648](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:649)
          return hook(config_settings)
[649](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:650)
        File "/tmp/pip-build-env-lasxk9xl/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
[650](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:651)
          return self._get_build_requires(config_settings, requirements=['wheel'])
[651](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:652)
        File "/tmp/pip-build-env-lasxk9xl/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
[652](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:653)
          self.run_setup()
[653](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:654)
        File "/tmp/pip-build-env-lasxk9xl/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
[654](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:655)
          exec(code, locals())
[655](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:656)
        File "<string>", line 99, in <module>
[656](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:657)
        File "<string>", line 95, in setup_package
[657](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:658)
        File "/tmp/pip-build-env-lasxk9xl/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
[658](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:659)
          return distutils.core.setup(**attrs)
[659](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:660)
        File "/tmp/pip-build-env-lasxk9xl/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 159, in setup
[660](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:661)
          dist.parse_config_files()
[661](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:662)
        File "/tmp/pip-build-env-lasxk9xl/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 898, in parse_config_files
[662](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:663)
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
[663](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:664)
        File "/tmp/pip-build-env-lasxk9xl/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 66, in apply_configuration
[664](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:665)
          config = read_configuration(filepath, True, ignore_option_errors, dist)
[665](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:666)
        File "/tmp/pip-build-env-lasxk9xl/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 128, in read_configuration
[666](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:667)
          validate(subset, filepath)
[667](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:668)
        File "/tmp/pip-build-env-lasxk9xl/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 55, in validate
[668](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:669)
          raise ValueError(f"{error}\n{summary}") from None
[669](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:670)
      ValueError: invalid pyproject.toml config: `project`.
[670](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:671)
      configuration error: `project` must contain ['name'] properties
[671](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:672)
      [end of output]
[672](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:673)
  
[673](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:674)
  note: This error originates from a subprocess, and is likely not a problem with pip.
[674](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:675)
error: subprocess-exited-with-error
[675](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:676)

[676](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:677)
× Getting requirements to build wheel did not run successfully.
[677](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:678)
│ exit code: 1
[678](https://github.com/tskit-dev/tutorials/actions/runs/5542001264/jobs/10116121615?pr=244#step:5:679)
╰─> See above for output.
```

**Comment by benjeffery** [comment]
I believe this is fixed now
